theme: just-the-docs

title: ModuPlane Pro
description: Advanced Unity Input & UI Framework featuring mode-less interaction.

url: "https://decnet-games.github.io"
baseurl: "/ModuPlanePro-Doc"

aux_links:
  "GitHub Repository":
    - "//github.com/DecNet-Games/ModuPlanePro-Doc"

color_scheme: dark

footer_content: "Copyright &copy; 2026 DecNet Games. All rights reserved."
